# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# === Basic configuration ===

# Your application's name
appname: "BMW::CSC::Diagnoser"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# === Engines ===
#
# NOTE: All the engine configurations need to be under a single "engines:"
# key.  If you uncomment engine configurations below, make sure to delete
# all "engines:" lines except the first.  Otherwise, only the last
# "engines:" block will take effect.

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"
engines:
  template:
    template_toolkit:
      # Note: start_tag and end_tag are regexes
      start_tag: '[%'
      end_tag:   '%]'

# session engine
#
# Simple: in-memory session store - Dancer2::Session::Simple
# YAML: session stored in YAML files - Dancer2::Session::YAML
#
# Check out metacpan for other session storage options:
# https://metacpan.org/search?q=Dancer2%3A%3ASession&search_type=modules
#
# Default value for 'cookie_name' is 'dancer.session'. If you run multiple
# Dancer apps on the same host then you will need to make sure 'cookie_name'
# is different for each app.
#
#engines:
#  session:
#    Simple:
#      cookie_name: testapp.session
#
#engines:
#  session:
#    YAML:
#      cookie_name: eshop.session
#      is_secure: 1
#      is_http_only: 1

device: "/dev/ttyUSB0"
csc_ids:
  1:
    '0100':
      type: unknown
    '0120':
      type: voltage
    '0130':
      type: voltage
    '0140':
      type: voltage
    '0150':
      type: voltage
    '0160':
      type: voltage
    '0170':
      type: voltage
    '0180':
      type: unknown
    '01C0':
      type: unknown
    '01D0':
      type: unknown
    '01E0':
      type: unknown
    '0200':
      type: unknown
  2:
    '0101':
      type: unknown
    '0121':
      type: voltage
    '0131':
      type: voltage
    '0141':
      type: voltage
    '0151':
      type: voltage
    '0161':
      type: voltage
    '0171':
      type: voltage
    '0181':
      type: unknown
    '01C1':
      type: unknown
    '01D1':
      type: unknown
    '01E1':
      type: unknown
    '0201':
      type: unknown
  3:
    '0102':
      type: unknown
    '0122':
      type: voltage
    '0132':
      type: voltage
    '0142':
      type: voltage
    '0152':
      type: voltage
    '0162':
      type: voltage
    '0172':
      type: voltage
    '0182':
      type: unknown
    '01C2':
      type: unknown
    '01D2':
      type: unknown
    '01E2':
      type: unknown
    '0202':
      type: unknown
  4:
    '0103':
      type: unknown
    '0123':
      type: voltage
    '0133':
      type: voltage
    '0143':
      type: voltage
    '0153':
      type: voltage
    '0163':
      type: voltage
    '0173':
      type: voltage
    '0183':
      type: unknown
    '01C3':
      type: unknown
    '01D3':
      type: unknown
    '01E3':
      type: unknown
    '0203':
      type: unknown
  5:
    '0104':
      type: unknown
    '0124':
      type: voltage
    '0134':
      type: voltage
    '0144':
      type: voltage
    '0154':
      type: voltage
    '0164':
      type: voltage
    '0174':
      type: voltage
    '0184':
      type: unknown
    '01C4':
      type: unknown
    '01D4':
      type: unknown
    '01E4':
      type: unknown
    '0204':
      type: unknown
  6:
    '0105':
      type: unknown
    '0125':
      type: voltage
    '0135':
      type: voltage
    '0145':
      type: voltage
    '0155':
      type: voltage
    '0165':
      type: voltage
    '0175':
      type: voltage
    '0185':
      type: unknown
    '01C5':
      type: unknown
    '01D5':
      type: unknown
    '01E5':
      type: unknown
    '0205':
      type: unknown