# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# === Basic configuration ===

# Your application's name
appname: "BMW::CSC::Diagnoser"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# === Engines ===
#
# NOTE: All the engine configurations need to be under a single "engines:"
# key.  If you uncomment engine configurations below, make sure to delete
# all "engines:" lines except the first.  Otherwise, only the last
# "engines:" block will take effect.

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"
engines:
  template:
    template_toolkit:
      # Note: start_tag and end_tag are regexes
      start_tag: '[%'
      end_tag:   '%]'

# session engine
#
# Simple: in-memory session store - Dancer2::Session::Simple
# YAML: session stored in YAML files - Dancer2::Session::YAML
#
# Check out metacpan for other session storage options:
# https://metacpan.org/search?q=Dancer2%3A%3ASession&search_type=modules
#
# Default value for 'cookie_name' is 'dancer.session'. If you run multiple
# Dancer apps on the same host then you will need to make sure 'cookie_name'
# is different for each app.
#
#engines:
#  session:
#    Simple:
#      cookie_name: testapp.session
#
#engines:
#  session:
#    YAML:
#      cookie_name: eshop.session
#      is_secure: 1
#      is_http_only: 1

device: "/dev//ttyUSB0"
csc_ids:
  1:
    - '0100'
    - '0120'
    - '0130'
    - '0140'
    - '0150'
    - '0160'
    - '0170'
    - '0180'
    - '01C0'
    - '01D0'
    - '01E0'
    - '0200'
  2:
    - '0101'
    - '0121'
    - '0131'
    - '0141'
    - '0151'
    - '0161'
    - '0171'
    - '0181'
    - '01C1'
    - '01D1'
    - '01E1'
    - '0201'
  3:
    - '0102'
    - '0122'
    - '0132'
    - '0142'
    - '0152'
    - '0162'
    - '0172'
    - '0182'
    - '01C2'
    - '01D2'
    - '01E2'
    - '0202'
  4:
    - '0103'
    - '0123'
    - '0133'
    - '0143'
    - '0153'
    - '0163'
    - '0173'
    - '0183'
    - '01C3'
    - '01D3'
    - '01E3'
    - '0203'
  5:
    - '0104'
    - '0124'
    - '0134'
    - '0144'
    - '0154'
    - '0164'
    - '0174'
    - '0184'
    - '01C4'
    - '01D4'
    - '01E4'
    - '0204'
  6:
    - '0105'
    - '0125'
    - '0135'
    - '0145'
    - '0155'
    - '0165'
    - '0175'
    - '0185'
    - '01C5'
    - '01D5'
    - '01E5'
    - '0205'