# Configuration for BMW CAN bus message interpretation.
# Each CSC contains a map of its known CAN IDs.
#
# Types can be 'voltage', 'temperature', 'total_voltage', or 'unknown'.
#
# For 'voltage' types, 'cell_map' maps the zero-based start
# byte (2, 4, 6) to the one-based cell number.
#
# For 'temperature' types, 'sensor_map' maps the zero-based
# start byte (5, 6, 7) to the one-based sensor number.
#
# For 'total_voltage' types, the last two bytes of the data payload
# are used.

# Configuration for BMW CAN bus message interpretation.
# Each CSC contains a map of its known CAN IDs.
#
# 'cell_map' maps the zero-based start byte to the one-based cell number.
# For all voltage messages, the format is now:
#   Bytes 7-8 (index 6): First cell in message
#   Bytes 5-6 (index 4): Second cell in message
#   Bytes 3-4 (index 2): Third cell in message

csc_ids:
  1:
    '0100':
      type: unknown
    '0120':
      type: voltage
      cell_map:
        6: 1
        4: 2
        2: 3
    '0130':
      type: voltage
      cell_map:
        6: 4
        4: 5
        2: 6
    '0140':
      type: voltage
      cell_map:
        6: 7
        4: 8
        2: 9
    '0150':
      type: voltage
      cell_map:
        6: 10
        4: 11
        2: 12
    '0160':
      type: voltage
      cell_map:
        6: 13
        4: 14
        2: 15
    '0170':
      type: voltage
      cell_map:
        6: 16
    '0180':
      type: temperature
      sensor_map:
        5: 1
        6: 2
        7: 3
    '01C0':
      type: unknown
    '01D0':
      type: unknown
    '01E0':
      type: total_voltage
    '0200':
      type: unknown
  2:
    '0101':
      type: unknown
    '0121':
      type: voltage
      cell_map:
        6: 1
        4: 2
        2: 3
    '0131':
      type: voltage
      cell_map:
        6: 4
        4: 5
        2: 6
    '0141':
      type: voltage
      cell_map:
        6: 7
        4: 8
        2: 9
    '0151':
      type: voltage
      cell_map:
        6: 10
        4: 11
        2: 12
    '0161':
      type: voltage
      cell_map:
        6: 13
        4: 14
        2: 15
    '0171':
      type: voltage
      cell_map:
        6: 16
    '0181':
      type: temperature
      sensor_map:
        5: 1
        6: 2
        7: 3
    '01C1':
      type: unknown
    '01D1':
      type: unknown
    '01E1':
      type: total_voltage
    '0201':
      type: unknown
  3:
    '0102':
      type: unknown
    '0122':
      type: voltage
      cell_map:
        6: 1
        4: 2
        2: 3
    '0132':
      type: voltage
      cell_map:
        6: 4
        4: 5
        2: 6
    '0142':
      type: voltage
      cell_map:
        6: 7
        4: 8
        2: 9
    '0152':
      type: voltage
      cell_map:
        6: 10
        4: 11
        2: 12
    '0162':
      type: voltage
      cell_map:
        6: 13
        4: 14
        2: 15
    '0172':
      type: voltage
      cell_map:
        6: 16
    '0182':
      type: temperature
      sensor_map:
        5: 1
        6: 2
        7: 3
    '01C2':
      type: unknown
    '01D2':
      type: unknown
    '01E2':
      type: total_voltage
    '0202':
      type: unknown
  4:
    '0103':
      type: unknown
    '0123':
      type: voltage
      cell_map:
        6: 1
        4: 2
        2: 3
    '0133':
      type: voltage
      cell_map:
        6: 4
        4: 5
        2: 6
    '0143':
      type: voltage
      cell_map:
        6: 7
        4: 8
        2: 9
    '0153':
      type: voltage
      cell_map:
        6: 10
        4: 11
        2: 12
    '0163':
      type: voltage
      cell_map:
        6: 13
        4: 14
        2: 15
    '0173':
      type: voltage
      cell_map:
        6: 16
    '0183':
      type: temperature
      sensor_map:
        5: 1
        6: 2
        7: 3
    '01C3':
      type: unknown
    '01D3':
      type: unknown
    '01E3':
      type: total_voltage
    '0203':
      type: unknown
  5:
    '0104':
      type: unknown
    '0124':
      type: voltage
      cell_map:
        6: 1
        4: 2
        2: 3
    '0134':
      type: voltage
      cell_map:
        6: 4
        4: 5
        2: 6
    '0144':
      type: voltage
      cell_map:
        6: 7
        4: 8
        2: 9
    '0154':
      type: voltage
      cell_map:
        6: 10
        4: 11
        2: 12
    '0164':
      type: voltage
      cell_map:
        6: 13
        4: 14
        2: 15
    '0174':
      type: voltage
      cell_map:
        6: 16
    '0184':
      type: temperature
      sensor_map:
        5: 1
        6: 2
        7: 3
    '01C4':
      type: unknown
    '01D4':
      type: unknown
    '01E4':
      type: total_voltage
    '0204':
      type: unknown
  6:
    '0105':
      type: unknown
    '0125':
      type: voltage
      cell_map:
        6: 1
        4: 2
        2: 3
    '0135':
      type: voltage
      cell_map:
        6: 4
        4: 5
        2: 6
    '0145':
      type: voltage
      cell_map:
        6: 7
        4: 8
        2: 9
    '0155':
      type: voltage
      cell_map:
        6: 10
        4: 11
        2: 12
    '0165':
      type: voltage
      cell_map:
        6: 13
        4: 14
        2: 15
    '0175':
      type: voltage
      cell_map:
        6: 16
    '0185':
      type: temperature
      sensor_map:
        5: 1
        6: 2
        7: 3
    '01C5':
      type: unknown
    '01D5':
      type: unknown
    '01E5':
      type: total_voltage
    '0205':
      type: unknown
